server:
  port: 7001
spring:
  devtools:
    restart:
      enabled: true
eureka:
  instance:
    hostname: localhost # Eureka服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向eureka注册中心注册自己
    fetch-registry: false # 表示是否向eureka注册中心注册自己
    serviceUrl:
      defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/

